### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 7272) exited unexpectedly

### ISSUE THREAD

**Issue by songwanguw** [songwanguw/text_gen#5]
```
:~/work/transV432/text_gen/examples/seq2seq$ 
ln -s ~/mount/csi_modeling/data data
export CUDA_VISIBLE_DEVICES=0,1,2,3
python finetune.py --learning_rate 3e-5 --fp16 --gpus 4 \
  --do_train \
  --val_check_interval 0.5 --n_val 80000 \
  --data_dir data/train_dev_conv_sum/gpt3_data_bart/train_data/ \
  --train_batch_size 6 --eval_batch_size 6 --num_train_epochs 20 \
  --max_target_length 102 --val_max_target_length 102 --test_max_target_length 120  \
  --num_workers 2 \
  --eval_max_gen_length 102 \
  --output_dir data/train_dev_conv_sum/gpt3_data_bart/bart_xsum_12_3_min11-max100-b96 \
  --model_name_or_path sshleifer/distilbart-xsum-12-3 \
  --accumulate_grad_batches 4 --overwrite_output_dir

````

Traceback (most recent call last):
  File "finetune.py", line 442, in <module>
    main(args)
  File "finetune.py", line 417, in main
    logger=logger,
  File "/mnt/sdb/sonwang/work/transV432/text_gen/examples/lightning_base.py", line 389, in generic_train
    trainer.fit(model)
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 282, in ddp_train
    results = self.train_or_test()
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 493, in train
    self.train_loop.run_training_epoch()
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 554, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/profiler/profilers.py", line 80, in profile_iterable
    value = next(iterator)
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 46, in _with_is_last
    last = next(it)
  File "/home/sonwang/anaconda3/envs/text_gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/xxx/anaconda3/envs/text_gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/xxxx/anaconda3/envs/text_gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/home/xxx/anaconda3/envs/text_gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 7272) exited unexpectedly
Exception ignored in: <function tqdm.__del__ at 0x7ff9864593b0>
Traceback (most recent call last):
  File "/home/xxxanaconda3/envs/text_gen/lib/python3.7/site-packages/tqdm/std.py", line 1145, in __del__
  File "/home/xxx/anaconda3/envs/text_gen/lib/python3.7/site-packages/tqdm/std.py", line 1299, in close
  File "/home/xxx/anaconda3/envs/text_gen/lib/python3.7/site-packages/tqdm/std.py", line 1492, in display
  File "/home/xxx/anaconda3/envs/text_gen/lib/python3.7/site-packages/tqdm/std.py", line 1148, in __str__
  File "/home/xxx/anaconda3/envs/text_gen/lib/python3.7/site-packages/tqdm/std.py", line 1450, in format_dict
**TypeError: cannot unpack non-iterable NoneType object**

**Comment by songwanguw** [comment]
My solution is to set `--num_workers 0 `

**Comment by songwang41** [comment]
also works `--num_workers 1`
